import localFont from "next/font/local";
import "./globals.css";
import Footer from "./componnet/footer/footer";
import NavBanner from "./componnet/navBanner/navBanner";
import Navbar from "./componnet/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Highfield center- Your dream our success",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBanner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
